-- SIKEKAR Kaltim - Supabase starter schema
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text check (role in ('admin','inspektur','pelaku_usaha','pemerintah','pln','masyarakat')) default 'masyarakat',
  phone text,
  agency text,
  created_at timestamptz default now()
);
create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  name text not null,
  sector text,
  regency text,
  district text,
  village text,
  address text,
  latitude double precision,
  longitude double precision,
  license_status text,
  created_at timestamptz default now()
);
create table if not exists public.inspections (
  id bigint generated by default as identity primary key,
  business_id bigint references public.businesses(id) on delete set null,
  inspector_id uuid references public.profiles(id) on delete set null,
  inspection_date date default current_date,
  category text,
  finding text,
  severity text,
  corrective_action text,
  due_date date,
  status text default 'open',
  latitude double precision,
  longitude double precision,
  created_at timestamptz default now()
);
create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  location text,
  category text,
  description text,
  status text default 'new',
  created_at timestamptz default now()
);
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text,
  category text,
  published boolean default false,
  published_at timestamptz,
  created_at timestamptz default now()
);
